# Generated by Django 4.1.2 on 2022-10-12 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('git_url', models.CharField(max_length=200)),
                ('git_branch', models.CharField(max_length=200)),
                ('git_commit_hash', models.CharField(max_length=200)),
                ('base_pcrs', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.UUIDField()),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('schedule', models.DurationField()),
                ('date_time', models.DateTimeField()),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider.app')),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iudx_id', models.UUIDField()),
            ],
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField()),
                ('result', models.JSONField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider.job')),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider.provider'),
        ),
    ]
