# Generated by Django 4.1.2 on 2022-10-14 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='resource_id',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='run',
            name='status',
            field=models.CharField(choices=[('R', 'Running'), ('S', 'Success'), ('F', 'Failure'), ('K', 'Killed')], default='F', max_length=1),
            preserve_default=False,
        ),
    ]
