# Generated by Django 4.1.2 on 2022-10-26 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0002_job_resource_id_run_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='schedule',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
