# Generated by Django 4.1.2 on 2022-10-26 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0004_alter_run_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='run_id',
            field=models.UUIDField(default='00000000-0000-0000-0000-000000000000'),
            preserve_default=False,
        ),
    ]
