# Generated by Django 4.1.6 on 2023-06-02 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("provider", "0005_run_run_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="run",
            name="status_info",
            field=models.JSONField(default=dict),
        ),
    ]
