# Generated by Django 4.1.6 on 2023-10-09 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("provider", "0006_run_status_info"),
    ]

    operations = [
        migrations.AddField(
            model_name="app",
            name="execution_platform",
            field=models.CharField(
                choices=[("NITRO", "AWS Nitro"), ("SGX", "Intel SGX")],
                default="NITRO",
                max_length=5,
            ),
            preserve_default=False,
        ),
    ]
