# Generated by Django 4.2.6 on 2024-05-02 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("provider", "0007_app_execution_platform"),
    ]

    operations = [
        migrations.AlterField(
            model_name="app",
            name="execution_platform",
            field=models.CharField(
                choices=[
                    ("NITRO", "AWS Nitro"),
                    ("SGX", "Intel SGX"),
                    ("AZURE AMD SEV", "Azure AMD SEV"),
                ],
                max_length=20,
            ),
        ),
    ]
