# Generated by Django 4.2.6 on 2024-08-28 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("provider", "0009_job_dataset_name_job_resource_server_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="additional_context",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
